version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./model:/app/model
    environment:
      - FLASK_APP=api/banana_deficiency_api.py
      - FLASK_ENV=production
      - PORT=5000
    restart: unless-stopped 